name: CI/CD with Kubernetes

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build Docker image
        run: docker build -t yogevfarjoun/winning-award-website:latest .

      - name: Push Docker image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push yogevfarjoun/winning-award-website:latest

  deploy:
    name: Deploy to Minikube via Helm
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Helm chart
        uses: actions/checkout@v4

      - name: Helm upgrade release
        run: |
          helm upgrade --install my-react-app ./my-react-app-chart \
            --namespace demo-app \
            --set image.repository=yogevfarjoun/winning-award-website \
            --set image.tag=latest
