replicaCount: 2

image:
  repository: docker.io/yogevfarjoun/winning-award-website
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecretName: dockerhub-creds # השאר ריק אם אין צורך, או מחק את המפתח

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: award.local
  className: nginx
  annotations: {}

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

pvc:
  enabled: true
  name: nginx-pvc
  accessModes: ["ReadWriteOnce"]
  storage: 1Gi
