apiVersion: apps/v1
kind: Deployment
metadata:
  name: award-website
  namespace: demo-app
  labels:
    app: award-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: award-website
  template:
    metadata:
      labels:
        app: award-website
    spec:
      containers:
        - name: web
          image: docker.io/yogevfarjoun/winning-award-website:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: "/", port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "200m", memory: "256Mi" }
